# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1igzISnrYd2t4s1QuHykqxf-kLuSwk8Q9
"""

import numpy as np
import matplotlib.pyplot as plt

#Sample size
simlen = 4900
# Generate sample
y = np.random.randint(1,7, size=(simlen,3))
sum = 0
print("Sample used:",end="\n")
for i in range(simlen):
    if y[i][0]==6 :
        sum+=1
        print(y[i][0],"-","-",end="\n")
    elif y[i][1]==6 :
        sum+=0
        print(y[i][0],y[i][1],"-",end="\n")
    elif y[i][2]==6 :
        sum+=-1
        print(y[i][0],y[i][1],y[i][2],end="\n")
    else :
        sum+=-3
        print(y[i][0],y[i][1],y[i][2],end="\n")
print("Average money gained by the man experimentally =",(sum/simlen),end='\n')
print("Average money gained by the man theoretically is -1.685")