# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1igzISnrYd2t4s1QuHykqxf-kLuSwk8Q9
"""

import numpy as np
import matplotlib.pyplot as plt

#Sample size
simlen = 100000
# Generate sample
x = np.random.randint(1,7, size=(simlen,3))
amt_gained = 0
for i in range(simlen):
    if x[i][0]==6 :
        amt_gained+=1
    elif x[i][1]==6 :
        amt_gained+=0
    elif x[i][2]==6 :
        amt_gained+=-1
    else :
        amt_gained+=-3
print("Average money gained by the man experimentally =",(amt_gained/simlen),end='\n')
print("Average money gained by the man theoretically = -1.685\n")
print("Since the difference in absolute values",abs((sum/simlen) + 1.685),"is very small. We can say that the simulations are close to the theoretical Analysis.")
