# -*- coding: utf-8 -*-
"""Assign2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxexWaIw7cLsVPbBfYrbra1pR-vEsn4o
"""

import math


import numpy as np
import matplotlib.pyplot as plt

simlen = 10000
#When y=2, x has a uniform distribution
values = np.random.uniform(0.0,2.0,simlen)
sum = 0.0
for i in range(simlen):
    sum = sum + values[i]
expectation_value = sum/simlen
print("The Expectation value of X calculated theoretically is 1.")
print("The Expectation value of X calculated via simulation is ",expectation_value)
print("Since the difference in absolute values ",abs(expectation_value - 1)," is very small, we can say that the simulation is close to theoretical analysis.")